### ISSUE TITLE
cant run because "Error: No such option: -e"

### ISSUE THREAD

**Issue by cehuda1** [blackhatethicalhacking/TerminatorZ#13]
+-++-++-++-++-++-+ +-++-++-++-++-+
 |B||H||E||H||'||s| |W||O||R||L||D|
 +-++-++-++-++-++-+ +-++-++-++-++-+

Offensive Security Tip: The supreme art of war is to subdue the enemy without fighting. - Sun Tzu
MEANS, IT'S ☕ 1337 ⚡ TIME, 369 ☯
error: could not load font small

[YOUR ARE USING TerminatorZ.sh] - (v1.1) CODED BY Chris 'SaintDruG' Abou-Chabké WITH ❤ FOR blackhatethicalhacking.com for Educational Purposes only!
CHECKING IF YOU ARE CONNECTED TO THE INTERNET!
++++ CONNECTION FOUND, LET'S GO!
Enter the domain: (example.com)
google.com
Usage: httpx [OPTIONS] URL

Error: No such option: -e
Total URLs found: 0
┌────────────────────────────────────────────────────┐
│Let us Terminate them in 5 seconds - Matrix Mode ON:│
└────────────────────────────────────────────────────┘
Targets have been T3rm1nat3d... I'll be back!

**Comment by blackhatethicalhacking** [comment]
If you did not install httpx correctly, make sure to have it - and test it alone, then retry. Installing the pre-requirements is crucial for it to work

**Comment by cehuda1** [comment]
![gambar](https://user-images.githubusercontent.com/121425666/236808192-6de9a1ee-40f9-451a-8cab-b4b1662764fa.png)
i was corectly install for httpx but argument -e is none

**Comment by blackhatethicalhacking** [comment]
Thanks for sharing, it seems for some reason there is an issue calling httpx, from the tool.

In the tool there is no -e argument, if you check the source code, the part we use httpx is this:

`waybackurls $domain | grep -E "\.js$|\.php$|\.yml$|\.env$|\.txt$|\.xml$|\.config$" | httpx -verbose | sort -u | tee urls.txt lolcat
`

As you can see there is no option for -e

To test if everything is setup correctly using default tools, try running this first and update to latest version :

`waybackurls vulnweb.com | grep -E "\.js$|\.php$|\.yml$|\.env$|\.txt$|\.xml$|\.config$" | httpx -verbose | sort -u | tee urls.txt `

**Comment by unfairDude** [comment]
> rror: No such option: -e

i assume you are using kali.
delete the python script httpx located in usr/bin

**Comment by cehuda1** [comment]
its work thanks
