### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by fred-secludit** [blackhatethicalhacking/TerminatorZ#2]
Hi there,
It seems go get is deprecated for installing executables since version 1.17.
https://go.dev/doc/go-get-install-deprecation

"go get github.com/tomnomnom/waybackurls" should then be replaced by "go install github.com/tomnomnom/waybackurls@latest" as mentioned on waybackurls github page.

Best regards,
Fred

**Comment by blackhatethicalhacking** [comment]
Sure, seems tomnomnom needs to update their repo :) That's because of the recent changes in go, thanks for highlight !
