### ISSUE TITLE
Error: No such option: -e

### ISSUE THREAD

**Issue by j-0-y** [blackhatethicalhacking/TerminatorZ#28]
When I enter domain like, 
CHECKING IF YOU ARE CONNECTED TO THE INTERNET!
++++ CONNECTION FOUND, LET'S GO!
Enter the domain: (example.com) 
visa.com

I got - 
Usage: httpx [OPTIONS] URL

Error: No such option: -e

**Comment by blackhatethicalhacking** [comment]
You need to install the requirements, you got an issue with httpx.
