### ISSUE TITLE
working with tool getting error

### ISSUE THREAD

**Issue by osman876** [blackhatethicalhacking/TerminatorZ#4]
Enter the domain: 
testphp.vulnweb.com
./TerminatorZ.sh: line 38: waybackurls: command not found
Usage: httpx [OPTIONS] URL

Error: No such option: -e

please help me to resolve this issue

**Comment by blackhatethicalhacking** [comment]
Hello Osman, the tool works fine, the errors are coming because you did not install the requirements i have set:

./TerminatorZ.sh: line 38: waybackurls: command not found

Means, its not found, you got to install it by following the installation

**Comment by osman876** [comment]
i installed dependencies but i am still getting the same error

**Comment by osman876** [comment]
httpx --help
                                   HTTPX 🦋                                   

                        A next generation HTTP client.                        

Usage: httpx <URL> [OPTIONS]                                                  

                                                                              
 -m, --method METHOD             Request method, such as GET, POST, PUT,      
                                 PATCH, DELETE, OPTIONS, HEAD.                
                                 [Default: GET, or POST if a request body is  
                                 included]                                    
                                                                              
 -p, --params <NAME VALUE> ...   Query parameters to include in the request   
                                 URL.                                         
                                                                              
 -c, --content TEXT              Byte content to include in the request body. 
                                                                              
 -d, --data <NAME VALUE> ...     Form data to include in the request body.    
                                                                              
 -f, --files <NAME FILENAME> ... Form files to include in the request body.   
                                                                              
 -j, --json TEXT                 JSON data to include in the request body.    
                                                                              
 -h, --headers <NAME VALUE> ...  Include additional HTTP headers in the       
                                 request.                                     
                                                                              
 --cookies <NAME VALUE> ...      Cookies to include in the request.           
                                                                              
 --auth <USER PASS>              Username and password to include in the      
                                 request. Specify '-' for the password to use 
                                 a password prompt. Note that using           
                                 --verbose/-v will expose the Authorization   
                                 header, including the password encoding in a 
                                 trivially reversible format.                 
                                                                              
 --proxies URL                   Send the request via a proxy. Should be the  
                                 URL giving the proxy address.                
                                                                              
 --timeout FLOAT                 Timeout value to use for network operations, 
                                 such as establishing the connection, reading 
                                 some data, etc... [Default: 5.0]             
                                                                              
 --follow-redirects              Automatically follow redirects.              
                                                                              
 --no-verify                     Disable SSL verification.                    
                                                                              
 --http2                         Send the request using HTTP/2, if the remote 
                                 server supports it.                          
                                                                              
 --download FILE                 Save the response content as a file, rather  
                                 than displaying it.                          
                                                                              
 -v, --verbose                   Verbose output. Show request as well as      
                                 response.                                    
                                                                              
 --help                          Show this message and exit. 

httpx doesn't have parameter with "e"

**Comment by blackhatethicalhacking** [comment]
If you type this in your terminal:

waybackurls example.com

and get waybackurls: command not found

You must solve this issue first before using TerminatorZ one way is to download the package from waybackurls and make sure to copy it to /usr/local/bin or copy it to the same directory of TerminatorZ and make sure to give it chmod +x

The same with httpx, seems it is not updated.

Before you use TerminatorZ run echo "example.com" | httpx -verbose

Just like the tool:

<img width="594" alt="Screenshot 2023-02-18 at 2 01 01 PM" src="https://user-images.githubusercontent.com/13942386/219864631-33c80c18-e9c3-4485-bd12-7c223c7c0a12.png">

You cannot use the tool if you don't get them to work.

I just tested it for you again here, you can see the httpx version using, so make sure you first fix these, then try and it should work:

https://vimeo.com/800098663/00773935e3

**Comment by osman876** [comment]
now iam getting issue like this :(

 _____              _           _          ____
|_   _|__ _ _ _ __ (_)_ _  __ _| |_ ___ _ |_  /
  | |/ -_) '_| '  \| | ' \/ _` |  _/ _ \ '_/ /
  |_|\___|_| |_|_|_|_|_||_\__,_|\__\___/_|/___|


[YOUR ARE USING TerminatorZ.sh] - (v1.0) CODED BY Chris 'SaintDruG' Abou-Chabké WITH ❤ FOR blackhatethicalhacking.com for Educational Purposes only!
CHECKING IF YOU ARE CONNECTED TO THE INTERNET!
++++ CONNECTION FOUND, LET'S GO!
Enter the domain: 
testphp.vulnweb.com

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/              v1.2.7

		projectdiscovery.io

┌────────────────────────────────────┐
│Exiting the Matrix for 5 seconds in:│
└────────────────────────────────────┘
┌─┐
│3│
└─┘
┌─┐
│2│
└─┘
┌─┐
│1│
└─┘
00 11 01 10 11 00 10 01 11 00 01 10

**Comment by osman876** [comment]
finally working thanks a lot :)

**Comment by blackhatethicalhacking** [comment]
The tool is now working!

Just remove testphp.vulnweb.com

to vulnweb.com as you need to provide a domain, not a subdomain or URL: https://

Nice to hear! - Closing
