### ISSUE TITLE
Error: No such option: -e

### ISSUE THREAD

**Issue by TarunV-007** [blackhatethicalhacking/TerminatorZ#8]
[YOUR ARE USING TerminatorZ.sh] - (v1.1) CODED BY Chris 'SaintDruG' Abou-Chabké WITH ❤ FOR blackhatethicalhacking.com for Educational Purposes only!
CHECKING IF YOU ARE CONNECTED TO THE INTERNET!
++++ CONNECTION FOUND, LET'S GO!
Enter the domain: (example.com) 
vulnweb.com
Usage: httpx [OPTIONS] URL

Error: No such option: -e
Total URLs found: 0
./TerminatorZ.sh: line 107: toilet: command not found
Targets have been T3rm1nat3d... I'll be back!

**Comment by blackhatethicalhacking** [comment]
You have to fix the pre-required tools, it is saying it:

`./TerminatorZ.sh: line 107: toilet: command not found`

This means you must install 'toilet'

And 

`Error: No such option: -e`

Is for 'httpx' it is not installed correctly.

First, perform a git stash & git pull to make sure you have the latest version.

Then install both toilet and httpx, test them separately, and then run Terminator so it can work :)
