### ISSUE TITLE
0 vulns find on vulnable.com

### ISSUE THREAD

**Issue by unfairDude** [blackhatethicalhacking/TerminatorZ#9]
How is this scanner good if not working on vulnable.com?

0 vuln found!

**Comment by blackhatethicalhacking** [comment]
The tool works.

To answer your questions, vulnerable.com is not vulnerable...

testphp.vulnweb.com
vulnweb.com

For the website you are trying, you need permission.

**Comment by unfairDude** [comment]
> The tool works.
> 
> To answer your questions, vulnerable.com is not vulnerable...
> 
> testphp.vulnweb.com
> vulnweb.com
> 
> For the website you are trying, you need permission. 
> 
> 

i used vulnweb, it was misspelling sorry!

I also get these errors on startup

[Screenshot_2023-04-24-02-12-22-659_com.sonelli.juicessh.jpg](https://user-images.githubusercontent.com/102629559/234130459-298e7791-e3f1-4019-8c86-4378a9ea674e.jpg)
